# Generated by Django 5.1.5 on 2025-02-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='post',
            new_name='issue',
        ),
    ]
