# Generated by Django 5.1.5 on 2025-02-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_rename_post_reply_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tags',
            field=models.CharField(blank=True, choices=[('project0', 'Search'), ('project1', 'Wiki'), ('project2', 'Commerce'), ('project3', 'Mail'), ('project4', 'Network'), ('project6', 'Capstone')], max_length=100),
        ),
    ]
