# Generated by Django 5.1.5 on 2025-02-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_alter_issue_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tags',
            field=models.CharField(blank=True, choices=[('Project0 Search', 'Search'), ('Project1 Wiki', 'Wiki'), ('Project2 Commerce', 'Commerce'), ('Project3 Mail', 'Mail'), ('Project4 Network', 'Network'), ('Final Project', 'Capstone')], max_length=100),
        ),
    ]
