# Generated by Django 5.1.5 on 2025-02-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_alter_issue_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
